name: Java CI with Maven and NonDex









on: [push, pull_request]







jobs:


 build:


   runs-on: ubuntu-latest







   steps:


   - uses: actions/checkout@v2







   - name: Set up JDK 8


     uses: actions/setup-java@v2


     with:


       java-version: '8.0.322+6'


       distribution: 'adopt'







   - name: Build without tests


     run: mvn clean install -DskipTests -pl core -am







   - name: Run tests without NonDex


     run: mvn -pl core test -Dtest=com.alibaba.alink.operator.batch.audio.ExtractMfccFeatureBatchOpTest#testExtractMfccFeatureBatchOp







   - name: Run tests with NonDex


     run: mvn -pl core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.alibaba.alink.operator.batch.audio.ExtractMfccFeatureBatchOpTest#testExtractMfccFeatureBatchOp


